from typing import Protocol, List, Sequence, Any
from buildwatch.infrastructure.database.models.core.techniques import TechniquesORM


class TechniqueRepositoryProtocol(Protocol):
    async def create_technique(self, name: str, name_ru: str, color: str) -> int: ...
    async def get_techniques(
        self, *specs: Any, **filter_by: Any
    ) -> Sequence[TechniquesORM]: ...
    async def get_technique_by_id(
        self, technique_id: int, *specs: Any
    ) -> TechniquesORM | None: ...
    async def update_technique(self, technique_id: int, **kwargs: Any) -> None: ...
    async def delete_technique(self, technique_id: int) -> None: ...
    async def get_count(self, model: Any, *specs: Any, **filter_by: Any) -> int: ...
