services:
  build-watch-init:
    image: ghcr.io/build-watch-kiki/build-watch-backend:1.0.4

  build-watch-backend:
    image: ghcr.io/build-watch-kiki/build-watch-backend:1.0.4

  build-watch-backend-worker:
    image: ghcr.io/build-watch-kiki/build-watch-backend:1.0.4

  build-watch-cv:
    image: ghcr.io/build-watch-kiki/build-watch-cv:1.0.2

  build-watch-frontend:
    image: ghcr.io/build-watch-kiki/build-watch-frontend:1.0.2

  postgres:
    image: postgres@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722

  rabbitmq:
    image: rabbitmq@sha256:606d8c0d6b3c18d1da9afc53bc7cdb2a8d5486df91b5a9830e9e07626c9ae281

  minio:
    image: docker.io/bitnamilegacy/minio@sha256:50cec18ac4184af4671a78aedd5554942c8ae105d51a465fa82037949046da01
